#!/usr/bin/env perl

use 5.010;
use strict;
use warnings;
use FindBin '$Bin';
use lib "$Bin/../lib";

use Benchmark::Dumb qw(cmpthese);
use Text::ANSI::Util qw(ta_strip);

my $str_100char_10code = "\e[31m1234567890\e[0m\e[32m1234567890\e[0m" x 5;

cmpthese(0, {
    'ta_strip (100char_10code)' => sub { ta_strip($str_100char_10code) },
});
